@extends ('layout')

@section ('content')
<div class="Block Block--small">
    <h1 class="Block__heading Block__heading--red">Terms</h1>
        <div class="Block__info">
            <h3><strong>Gotogym.info and Team Gotogym.info Terms and Conditions of Use<br></strong></h3>
            <h4><strong>For Residents of Ukraine<br></strong><br></h4>

            Last Updated: May 7, 2016
            Gotogym.info, LLC and its affiliates, subsidiaries and parent companies (collectively, “Gotogym.info”, “us”, “we” or“our”) are pleased to provide you with access to and use of our websites, applications, content, streaming services, products, goods, equipment, services, promotions, software, technology and any other materials (collectively, “Gotogym.info Services”) that we may provide.<br><br>
            THE Gotogym.info SERVICES ARE NOT INTENDED FOR ANYONE UNDER THE AGE OF 13. IF YOU ARE 13 TO 17 YEARS OF AGE, YOU MUST ACCESS AND/OR USE ANY Gotogym.info SERVICES ONLY WITH THE INVOLVEMENT OF YOUR PARENT OR GUARDIAN.<br><br>
            <h4><strong>1. Contract Between You and Gotogym.info; Privacy Policy.<br><br></strong><br></h4>
            These Terms and Conditions of Use (“Terms”) and our Privacy Policy (available here) form a legally binding agreement between you and Gotogym.info, and govern your access and use, and our provision of, the Gotogym.info Services and any other technology, items or other materials on which these Terms are posted.<br><br>
             BY ACCESSING OR USING ANY Gotogym.info SERVICE, YOU AGREE TO BE BOUND AND ABIDE BY THESE TERMS, OUR PRIVACY POLICY AND ANY AMENDMENTS THERETO, AND YOU AGREE YOU ARE AT LEAST 13 YEARS OF AGE. PLEASE READ THESE TERMS CAREFULLY BEFORE USING ANY Gotogym.info SERVICES, ESPECIALLY SINCE THESE TERMS MAY AFFECT YOUR LEGAL RIGHTS, SUCH AS YOUR RIGHT TO BRING A LAWSUIT OR CLASS ACTION. IF YOU DO NOT AGREE TO THESE TERMS, PLEASE IMMEDIATELY CEASE USE OF ANY Gotogym.info SERVICES.<br><br>
            Supplemental terms and conditions may apply to certain Gotogym.info Services, such as rules for a particular contest, sweepstakes, competition, or activity, terms and conditions for Gotogym.info LIVE! Instructors, or terms that may accompany certain content, software or other materials accessible through the Gotogym.info Services (“Supplemental Terms”). Any Supplemental Terms will be disclosed to you in connection with those other activities and will apply and govern specifically over such activities.<br><br>
            Please note that for Team Gotogym.info Coaches, in the event of any direct conflict between these Terms and the Team Gotogym.info Coach Policies and Procedures and Compensation Plan (collectively, “P&P”) to which you agreed at the time you signed up as a Team Gotogym.info Coach, the P&P will govern and control.<br><br>
            <h4><strong>2. Changes to These Terms.</strong><br><br></h4>
            We may in our sole and absolute discretion change these Terms or our Privacy Policy from time to time to comply with laws or to meet our changing business requirements. These revisions shall be effective for new users immediately upon being posted to the Gotogym.info Services; however, for existing customers, the applicable revisions shall be effective 30 days after posting unless otherwise stated. If you do not agree with any of the changes, you must discontinue using any and all Gotogym.info Services.<br><br> By continuing to use any Gotogym.info Services after any changes are posted, you expressly accept any applicable changes. Please note our employees, customer service representatives, Team Gotogym.info independent Coach distributors, or other agents are not authorized to modify any provision of these Terms, either verbally or in writing.<br><br>
            <h4><strong>3. Gotogym.info’s Intellectual Property; Limited License to Gotogym.info Services.<br><br></strong><br></h4>
            You acknowledge and agree that the Gotogym.info Services, and any logos, names, designs, text, graphics, software, content, files, materials, and any other intellectual property rights contained therein, including without limitation any copyrights, patents, trademarks, proprietary or other rights arising therefrom are owned by Gotogym.info, LLC or its affiliates, licensors or suppliers. <br><br>
            Furthermore, you acknowledge and agree that the source and object code of certain Gotogym.info Services (such as our mobile applications) and the format, directories, queries, algorithms, structure and organization of the same are the intellectual property, proprietary and confidential information of Gotogym.info and its affiliates, licensors and suppliers. <br><br>You expressly agree that you will do nothing inconsistent with Gotogym.info’s ownership of the Gotogym.info Services, and that you gain no rights, title, or interest in or to any Gotogym.info Services, except as stated in these Terms or any executed written agreement between you and Gotogym.info. <br><br>
            In addition, except as expressly set forth in these Terms, you are not conveyed any right or license by implication, estoppel, or otherwise in or under any patent, trademark, copyright, or other proprietary right of Gotogym.info or any third party.<br><br>
            <h4><strong>B. Limited License.<br><br></strong><br></h4>
            For any Gotogym.info Services which enable you to use any software, content, or other materials owned or licensed by us only after you become validly authorized by us, we grant you a limited, revocable, non-exclusive, non-sublicensable, non-transferable license to access and use the specific Gotogym.info Services, and any related software, content, or other materials FOR YOUR PERSONAL, NON-COMMERCIAL USE ONLY.<br><br>
            <h4><strong>C. Restrictions.<br><br></strong><br></h4>
            You are prohibited from, and expressly agree that you will not:<br><br> (i) circumvent or disable any content protection system or digital rights management technology used with any Gotogym.info Services;<br><br> (ii) decompile, reverse engineer, disassemble or otherwise reduce any Gotogym.info Services to a human-readable form;<br><br> (iii) remove identification, copyright or other proprietary notices in or on the Gotogym.info Services;<br><br> (iv) access or use any Gotogym.info Services in an unlawful or unauthorized manner or in a manner that suggests an association with our content, products, services or brands, unless you have an executed agreement with us that allows for such activity;<br><br> (v) use, alter, copy, modify, store, sell, reproduce, distribute, republish, download, publicly perform, display, post, transmit, create derivative works of, or exploit any Gotogym.info Services or any part thereof, except as expressly authorized in these Terms or as part of the Gotogym.info Services provided to you; <br><br>(vi) introduce a virus or other harmful component, or otherwise tamper with, impair or damage any Gotogym.info Services or connected network, or interfere with any person or entity’s use or enjoyment of any Gotogym.info Services; <br><br>(vii) access, monitor, or copy any element of the Gotogym.info Services using a robot, spider, scraper or other automated means or manual process without our express written permission; <br><br>or (viii) sell, resell, or make commercial use of the Gotogym.info Services, unless you have an executed agreement with us that expressly allows for such activity.<br><br> You may not access or use any Gotogym.info Service in violation of Ukraine export control and economic sanctions requirements. By accessing or otherwise using any services, content or software through any Gotogym.info Services, you represent and warrant that: <br><br>(ix) your access to and use of the Gotogym.info Services, or any content or software therein, will comply with any and all requirements in these Terms; (x) you are not located in a country that is subject to a Ukrainian government embargo, or that has been designated by the Ukrainian government as a terrorist supporting country, and that you are not listed on any Ukrainian government list of prohibited or restricted parties; <br><br>and (xi) you will comply with all applicable local, national, and international laws, rules, regulations and ordinances in connection with your use of any Gotogym.info Services and our websites.<br><br>
            <h4><strong>D. Third Party Services and Content.<br><br></strong><br></h4>
            Certain Gotogym.info Services may integrate, be integrated into, or be provided in connection with third-party websites, services, content, and/or materials (“Third-Party Services”).<br><br> We do not review or control any Third-Party Services. We additionally make no claim or representation regarding, and accept no responsibility for, the quality, content, nature, or reliability of Third-Party Services accessible from our websites, apps, software or any other element of the Gotogym.info Services. There is no implied affiliation, endorsement or adoption by Gotogym.info of these Third-Party Services and we shall not be responsible for any content provided on or through these Third-Party Services. You should read the terms of use and privacy policies that apply to these Third-Party Services.<br><br>
            Certain opinions, advice, statements, or other information, including without limitation, food, nutrition and exercise data, may be made available by third parties through or in connection with the Gotogym.info Services (“Third-Party Content”). <br><br>This Third-Party Content belongs to the respective authors or providers of the applicable Third-Party Content and these authors and providers are solely responsible for the Third-Party Content they provide in connection with the Gotogym.info Services.<br><br> Gotogym.info DOES NOT: (I) GUARANTEE THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY THIRD-PARTY CONTENT ON ANY Gotogym.info SERVICE; OR (II) ADOPT, ENDORSE OR ACCEPT RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE OR STATEMENT MADE BY A THIRD-PARTY AS PART OF ANY THIRD-PARTY CONTENT. UNDER NO CIRCUMSTANCES WILL Gotogym.info BE RESPONSIBLE FOR ANY LOSS OR DAMAGE RESULTING FROM YOUR RELIANCE ON THIRD-PARTY CONTENT POSTED ON THE Gotogym.info SERVICES OR TRANSMITTED TO OR BY ANY THIRD-PARTY IN CONNECTION WITH THE Gotogym.info SERVICES.<br><br>
            <h4><strong>E. App Providers.<br><br></strong><br></h4>
            If you access any Gotogym.info Service using an Apple iOS or other third party device, you acknowledge that each of those third party companies, such as Apple Inc. (each, “App Provider”), will not be responsible for any damages arising out of the failure of a Gotogym.info Service to operate as intended.<br><br>
            When accessing any Gotogym.info Services by or through an App Provider, you acknowledge and agree that: (i) these Terms are concluded between you and Gotogym.info, and not with the App Provider, and that we are solely responsible for any Gotogym.info Services (such as mobile applications), and not the App Provider; (ii) the App Provider has no obligation to furnish any maintenance and support services with respect to any Gotogym.info Services; (iii) in the event of any failure of the Gotogym.info Services to conform to any applicable warranty: <br><br>(a) you may notify the App Provider and the App Provider will refund the purchase price for the Gotogym.info Services to you (if applicable); <br><br>(b) to the maximum extent permitted by applicable law, the App Provider will have no other warranty obligation whatsoever with respect to the Gotogym.info Services;<br><br> and (c) any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be our responsibility; (iv) the App Provider is not responsible for addressing any claims you have or any claims of any third party relating to any Gotogym.info Services or your possession and use of the Gotogym.info Services, including without limitation: <br><br>(d) product liability claims; <br><br>(e) any claim that the Gotogym.info Service fails to conform to any applicable legal or regulatory requirement; <br><br>and (f) claims arising under consumer protection or similar legislation;<br><br> (v) in the event of any third party claim that the Gotogym.info Service or your possession and use of the same infringes that third party’s intellectual property rights, we will be responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by these Terms;<br><br> (vi) the App Provider and its subsidiaries, are third party beneficiaries of these Terms as it relates to your license of the Gotogym.info Services, and that, upon your acceptance of these Terms, the App Provider will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third party beneficiary thereof;<br><br> and (vii) you must also comply with all applicable third party terms of service when using the Gotogym.info Services. As also mentioned in these Terms, you represent and warrant that you are not located in a country that is subject to a Ukrainian government embargo, or that has been designated by the Ukrainian government as a terrorist supporting country, and that you are not listed on any Ukrainian government list of prohibited or restricted parties.<br><br>
            <h4><strong>A. Submissions and Unsolicited Ideas Policies.<br><br></strong><br></h4>

             Gotogym.info is constantly developing new products, from fitness, to healthy supplements, to online applications, and more. Although we typically develop programs internally, we understand some people may be interested in submitting their ideas for possible development and marketing within the Gotogym.info business model.<br><br>
              Please note only those programs, products and ideas which promise to uphold, if not improve, on our standards and reputation for premium and innovative products may be considered for our brand portfolio. Since we are constantly working on dozens of new projects at any one time, and also provided with many overlapping ideas by individuals outside Gotogym.info, we cannot sign non-disclosure agreements to review any submissions or for follow up conversations, or promise that any ideas or products you submit are not already being developed by us. <br><br>In connection with anything you submit to us – whether or not solicited by us – you agree that creative ideas, suggestions or other materials you submit are not being made in confidence or trust and that no confidential or fiduciary relationship is intended or created between you and us in any way, and that you have no expectation of review, compensation or consideration of any type. If you agree with these Terms and believe your new product, program or idea will fit within our exclusive brand portfolio, you may send your ideas, product samples, training videos, or program demonstration submissions by following the instructions at www.Gotogym.info<br><br>

            <h4><strong>B. International Users.</strong><br><br></h4> 
            Our websites are controlled, operated, and administered by Gotogym.info from its offices within the Ukraine of America. Gotogym.info makes no representation or warranty that the materials contained within our websites are appropriate or available for use at other locations outside of the Ukraine, and access to them from territories where the contents or products available through the websites are illegal is prohibited. You may not use the websites or export the content or products in violation of Ukrainian export laws and regulations. If you access our websites from a location outside of the Ukraine, you are responsible for compliance with any and all local laws, rules, regulations and ordinances.<br><br>
            <h4><strong>C. Notices. </strong><br><br></h4> 

            All notices required or permitted to be given under these Terms must be in writing. Gotogym.info may provide you notice by sending you an e-mail to the address on file with us, which you agree electronically satisfies any legal requirement that such notice be in writing.<br><br> YOU BEAR THE SOLE RESPONSIBILITY OF ENSURING THAT YOUR E-MAIL ADDRESS ON FILE WITH Gotogym.info IS ACCURATE AND CURRENT, AND NOTICE TO YOU SHALL BE DEEMED EFFECTIVE UPON THE SENDING BY Gotogym.info OF AN EMAIL TO THAT ADDRESS.<br><br> You shall give any notice to Gotogym.info by means of Ukrainian mail, postage prepaid, to Gotogym.info, LLC, 3301 Exposition Blvd., Santa Monica, CA 90404, Attn: Legal Department. Such notice to Gotogym.info shall be effective upon receipt of notice by Gotogym.info.<br><br>
            <h4><strong>D. Severability. </strong><br><br></h4> 

            If any provision of these Terms (except for Section 9), or a part thereof, shall be unlawful, void or for any reason unenforceable, then that provision or part thereof shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions or parts thereof.<br><br>
            <h4><strong>E. Termination.</strong><br><br></h4> 

            Notwithstanding anything to the contrary in these Terms, Gotogym.info reserves the right, without notice and in its sole and absolute discretion, for any reason or no reason, to terminate your access and use of any Gotogym.info Services, including to block or prevent your access and use of any of our websites. You agree that Gotogym.info shall not be liable for any termination of your access and/or use of our websites.<br><br>
            <h4><strong>F. No Third Party Beneficiaries. </strong><br><br></h4> 

            Except as set forth in these Terms, only you and Gotogym.info may enforce these Terms; no third party shall be entitled to enforce these Terms.<br><br>
            <h4><strong>G. Survival.</strong><br><br></h4> 

            The provisions of these Terms which by their nature should survive the termination of these Terms shall survive such termination.<br><br>
            <h4><strong>H. Waiver.</strong><br><br></h4> 

            No waiver of any provision of these Terms by us shall be deemed a further or continuing waiver of such provision or any other provision, and our failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. Any waiver must be in writing signed by the Chief Legal Officer of Gotogym.info in order to be effective.<br><br>
            <h4><strong>I. Assignment.</strong><br><br></h4> 

            Gotogym.info may assign these Terms to any person or entity at any time, for any reason, with or without notice to you.<br><br>
            <h4><strong>J. Amendments</strong><br><br></h4> 

            Entire Agreement. These Terms may not be amended unless in a signed writing by an executive (Vice President or above in title) of Gotogym.info. These Terms constitute the final, exclusive and complete agreement between you and Gotogym.info regarding the subject matter hereof and supersede all agreements, communications and course of dealings between you and Gotogym.info.
            <h4><strong>K. Language.</strong><br><br></h4> 
            It is the express intent of the parties that these Terms and all related documents have been written in English.

        </div>
</div>
@stop
